// packages/svelte/src/components/Checkbox/Checkbox.svelte
<!-- packages/svelte/src/components/Checkbox/Checkbox.svelte -->
<script lang="ts">
    import { cn } from '../../utils';
    import { 
      checkboxStyles, 
      checkboxLabelStyles, 
      type CheckboxCoreProps, 
      type CheckboxStyleProps 
    } from '@mild-ui/core';
    
    type $$Props = CheckboxCoreProps & CheckboxStyleProps & {
      value?: string;
      'on:change'?: (event: Event) => void;
    };
    
    export let checked: $$Props['checked'] = false;
    export let disabled: $$Props['disabled'] = false;
    export let required: $$Props['required'] = false;
    export let name: $$Props['name'] = undefined;
    export let value: $$Props['value'] = undefined;
    export let indeterminate: $$Props['indeterminate'] = false;
    export let className: $$Props['className'] = '';
    export let size: $$Props['size'] = 'md';
    
    const checkboxClass = cn(
      checkboxStyles({ size }),
      className
    );
    
    const labelClass = cn(
      checkboxLabelStyles({ size })
    );
    
    $: if (indeterminate !== undefined) {
      if (typeof document !== 'undefined') {
        const element = document.getElementById($$restProps.id ?? '');
        if (element && element instanceof HTMLInputElement) {
          element.indeterminate = indeterminate;
        }
      }
    }
  </script>
  
  <div class="flex items-center space-x-2">
    <input
      type="checkbox"
      class={checkboxClass}
      {checked}
      {disabled}
      {required}
      {name}
      {value}
      on:change
      {...$$restProps}
    />
    {#if $$slots.default}
      <slot />
    {/if}
  </div>

// packages/vue/src/components/Checkbox/Checkbox.vue
<!-- packages/vue/src/components/Checkbox/Checkbox.vue -->
<template>
  <div class="flex items-center space-x-2">
    <input
      type="checkbox"
      :class="checkboxClasses"
      :checked="modelValue"
      :disabled="disabled"
      :required="required"
      :name="name"
      :value="value"
      @change="onChange"
      v-bind="$attrs"
    />
    <slot v-if="$slots.default" />
    <label
      v-else-if="label"
      :for="$attrs.id as string | undefined"
      :class="labelClasses"
    >
      {{ label }}
    </label>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import {
  checkboxStyles,
  checkboxLabelStyles,
  type CheckboxCoreProps,
  type CheckboxStyleProps,
} from "@mild-ui/core";
import { cn } from "../../utils";

interface Props extends CheckboxCoreProps, CheckboxStyleProps {
  modelValue?: boolean;
  label?: string;
}

const props = withDefaults(defineProps<Props>(), {
  size: "md",
  disabled: false,
  required: false,
  modelValue: false,
});

const emit = defineEmits<{
  (e: "update:modelValue", value: boolean): void;
}>();

const checkboxClasses = computed(() => {
  return cn(checkboxStyles({ size: props.size }), props.className);
});

const labelClasses = computed(() => {
  return cn(checkboxLabelStyles({ size: props.size }));
});

const onChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit("update:modelValue", target.checked);
};
</script>
