// packages/react/src/providers/ThemeProvider.tsx
import React, { createContext, useContext, useEffect, useState } from "react";
import {
  ThemeConfig,
  defaultTheme,
  darkTheme,
  applyTheme,
} from "@mild-ui/core";

type ThemeMode = "light" | "dark" | "system";

interface ThemeContextType {
  theme: ThemeMode;
  setTheme: (theme: ThemeMode) => void;
  config: ThemeConfig;
  setConfig: (config: ThemeConfig) => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

interface ThemeProviderProps {
  children: React.ReactNode;
  defaultTheme?: ThemeMode;
  config?: ThemeConfig;
  storageKey?: string;
}

export function ThemeProvider({
  children,
  defaultTheme: initialTheme = "system",
  config = defaultTheme,
  storageKey = "mild-ui-theme",
}: ThemeProviderProps) {
  const [theme, setThemeState] = useState<ThemeMode>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem(storageKey) as ThemeMode) || initialTheme;
    }
    return initialTheme;
  });

  const [themeConfig, setThemeConfig] = useState<ThemeConfig>(config);

  const setTheme = (newTheme: ThemeMode) => {
    setThemeState(newTheme);
    if (typeof window !== "undefined") {
      localStorage.setItem(storageKey, newTheme);
    }
  };

  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove("light", "dark");

    let effectiveTheme: "light" | "dark";

    if (theme === "system") {
      effectiveTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
    } else {
      effectiveTheme = theme;
    }

    root.classList.add(effectiveTheme);

    // Apply the theme configuration
    const activeConfig = effectiveTheme === "dark" ? darkTheme : themeConfig;
    applyTheme(activeConfig);
  }, [theme, themeConfig]);

  // Listen for system theme changes
  useEffect(() => {
    if (theme !== "system") return;

    const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
    const handleChange = () => {
      const root = window.document.documentElement;
      root.classList.remove("light", "dark");
      root.classList.add(mediaQuery.matches ? "dark" : "light");

      const activeConfig = mediaQuery.matches ? darkTheme : themeConfig;
      applyTheme(activeConfig);
    };

    mediaQuery.addEventListener("change", handleChange);
    return () => mediaQuery.removeEventListener("change", handleChange);
  }, [theme, themeConfig]);

  return (
    <ThemeContext.Provider
      value={{
        theme,
        setTheme,
        config: themeConfig,
        setConfig: setThemeConfig,
      }}
    >
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error("useTheme must be used within a ThemeProvider");
  }
  return context;
}

// packages/vue/src/providers/ThemeProvider.vue
<template>
  <div>
    <slot
      :theme="theme"
      :setTheme="setTheme"
      :config="config"
      :setConfig="setConfig"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, provide, onMounted, watch, computed } from "vue";
import {
  ThemeConfig,
  defaultTheme,
  darkTheme,
  applyTheme,
} from "@mild-ui/core";

type ThemeMode = "light" | "dark" | "system";

interface Props {
  defaultTheme?: ThemeMode;
  config?: ThemeConfig;
  storageKey?: string;
}

const props = withDefaults(defineProps<Props>(), {
  defaultTheme: "system",
  config: () => defaultTheme,
  storageKey: "mild-ui-theme",
});

const theme = ref<ThemeMode>(props.defaultTheme);
const config = ref<ThemeConfig>(props.config);

// Initialize theme from localStorage
onMounted(() => {
  if (typeof window !== "undefined") {
    const stored = localStorage.getItem(props.storageKey) as ThemeMode;
    if (stored) {
      theme.value = stored;
    }
  }
  applyCurrentTheme();
});

const setTheme = (newTheme: ThemeMode) => {
  theme.value = newTheme;
  if (typeof window !== "undefined") {
    localStorage.setItem(props.storageKey, newTheme);
  }
};

const setConfig = (newConfig: ThemeConfig) => {
  config.value = newConfig;
};

const effectiveTheme = computed(() => {
  if (theme.value === "system") {
    if (typeof window !== "undefined") {
      return window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
    }
    return "light";
  }
  return theme.value;
});

const applyCurrentTheme = () => {
  if (typeof window === "undefined") return;

  const root = window.document.documentElement;
  root.classList.remove("light", "dark");
  root.classList.add(effectiveTheme.value);

  const activeConfig =
    effectiveTheme.value === "dark" ? darkTheme : config.value;
  applyTheme(activeConfig);
};

// Watch for theme changes
watch([theme, config], applyCurrentTheme);

// Listen for system theme changes
onMounted(() => {
  if (typeof window === "undefined") return;

  const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
  const handleChange = () => {
    if (theme.value === "system") {
      applyCurrentTheme();
    }
  };

  mediaQuery.addEventListener("change", handleChange);

  return () => {
    mediaQuery.removeEventListener("change", handleChange);
  };
});

// Provide theme context
provide("theme", {
  theme,
  setTheme,
  config,
  setConfig,
});
</script>
