// examples/react/src/components/Button/Button.tsx
import React from "react";

interface ButtonProps {
  variant?: "primary" | "secondary" | "outline" | "ghost";
  size?: "small" | "medium" | "large";
  disabled?: boolean;
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void;
  leadingIcon?: React.ReactNode;
  trailingIcon?: React.ReactNode;
  children: React.ReactNode;
  className?: string;
}

const Button = ({
  variant = "primary",
  size = "medium",
  disabled = false,
  onClick,
  leadingIcon,
  trailingIcon,
  children,
  className = "",
}: ButtonProps) => {
  const baseClasses = [
    "mild-button",
    `mild-button-${variant}`,
    `mild-button-${size}`,
  ].join(" ");

  return (
    <button
      className={`${baseClasses} ${className}`}
      disabled={disabled}
      onClick={onClick}
    >
      {leadingIcon && (
        <span className="mild-button-icon mild-button-leading-icon">
          {leadingIcon}
        </span>
      )}
      <span className="mild-button-content">{children}</span>
      {trailingIcon && (
        <span className="mild-button-icon mild-button-trailing-icon">
          {trailingIcon}
        </span>
      )}
    </button>
  );
};

export default Button;

// packages/vue/src/components/Button/Button.vue
<template>
    <button
      :class="[baseClasses, customClass]"
      :disabled="disabled"
      @click="onClick"
    >
      <span v-if="$slots['leading-icon']" class="mild-button-icon mild-button-leading-icon">
        <slot name="leading-icon"></slot>
      </span>
      <span class="mild-button-content">
        <slot></slot>
      </span>
      <span v-if="$slots['trailing-icon']" class="mild-button-icon mild-button-trailing-icon">
        <slot name="trailing-icon"></slot>
      </span>
    </button>
  </template>
  
  <script setup lang="ts">
  import { computed } from 'vue';
  import { getButtonAttributes, ButtonVariant, ButtonSize } from '@mild-ui/core';
  
  interface Props {
    variant?: ButtonVariant;
    size?: ButtonSize;
    disabled?: boolean;
    customClass?: string;
  }
  
  const props = withDefaults(defineProps<Props>(), {
    variant: 'primary',
    size: 'medium',
    disabled: false,
    customClass: ''
  });
  
  const emit = defineEmits<{
    (e: 'click', event: MouseEvent): void;
  }>();
  
  const baseClasses = computed(() => {
    const attrs = getButtonAttributes({
      variant: props.variant,
      size: props.size,
      disabled: props.disabled
    });
    return attrs.className;
  });
  
  const onClick = (event: MouseEvent) => {
    emit('click', event);
  };
  </script>
