// packages/svelte/src/components/Radio/Radio.svelte
<!-- packages/svelte/src/components/Radio/Radio.svelte -->
<script lang="ts">
    import { cn } from '../../utils';
    import { 
      radioStyles, 
      radioLabelStyles, 
      type RadioCoreProps, 
      type RadioStyleProps 
    } from '@mild-ui/core';
    
    type $$Props = RadioCoreProps & RadioStyleProps & {
      value?: string;
      'on:change'?: (event: Event) => void;
    };
    
    export let checked: $$Props['checked'] = false;
    export let disabled: $$Props['disabled'] = false;
    export let required: $$Props['required'] = false;
    export let name: $$Props['name'] = undefined;
    export let value: $$Props['value'];
    export let className: $$Props['className'] = '';
    export let size: $$Props['size'] = 'md';
    
    const radioClass = cn(
      radioStyles({ size }),
      className
    );
    
    const labelClass = cn(
      radioLabelStyles({ size })
    );
  </script>
  
  <div class="flex items-center space-x-2">
    <input
      type="radio"
      class={radioClass}
      {checked}
      {disabled}
      {required}
      {name}
      {value}
      on:change
      {...$$restProps}
    />
    {#if $$slots.default}
      <slot />
    {/if}
  </div>

// packages/react/src/components/Radio/Radio.tsx
// packages/react/src/components/Radio/Radio.tsx
import * as React from "react";
import * as RadioGroupPrimitive from "@radix-ui/react-radio-group";
import { Circle } from "lucide-react";
import {
  RadioCoreProps,
  radioStyles,
  RadioStyleProps,
  radioLabelStyles,
  RadioSize,
} from "@mild-ui/core";
import { cn } from "../../utils";

// Props untuk RadioGroup
interface RadioGroupProps
  extends React.ComponentPropsWithoutRef<typeof RadioGroupPrimitive.Root> {
  children?: React.ReactNode;
  className?: string;
  ui?: {
    contaier?: string;
    items?: string;
  };
}

// Props untuk RadioGroupItem
interface RadioGroupItemProps extends RadioCoreProps, RadioStyleProps {
  id?: string;
  className?: string;
  label?: string;
  value: string;
  disabled?: boolean;
  required?: boolean;
  name?: string;
}

// RadioGroup component
const RadioGroup = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  RadioGroupProps
>(({ className, ...props }, ref) => {
  return (
    <RadioGroupPrimitive.Root
      className={cn("grid gap-2", className)}
      {...props}
      ref={ref}
    />
  );
});
RadioGroup.displayName = "RadioGroup";

// RadioGroupItem component
const RadioGroupItem = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Item>,
  RadioGroupItemProps
>(
  (
    { className, size = "md", label, value, disabled, required, id, ...props },
    ref,
  ) => {
    const radioId = id || `radio-${value}`;

    return (
      <div className="flex items-center space-x-2">
        <RadioGroupPrimitive.Item
          ref={ref}
          className={cn(radioStyles({ size }), className)}
          value={value}
          disabled={disabled}
          required={required}
          id={radioId}
          {...props}
        >
          <RadioGroupPrimitive.Indicator className="flex items-center justify-center">
            <Circle className={cn("h-2.5 w-2.5 fill-current text-current")} />
          </RadioGroupPrimitive.Indicator>
        </RadioGroupPrimitive.Item>
        {label && (
          <label
            htmlFor={radioId}
            className={cn(
              radioLabelStyles({ size }),
              disabled && "opacity-50 cursor-not-allowed",
            )}
          >
            {label}
          </label>
        )}
      </div>
    );
  },
);
RadioGroupItem.displayName = "RadioGroupItem";

// Komponen Radio yang lebih fleksibel
interface RadioProps extends RadioGroupProps {
  items?: RadioGroupItemProps[];
  size?: RadioSize;
  defaultValue?: string;
  value?: string;
  onValueChange?: (value: string) => void;
}

const Radio = React.forwardRef<
  React.ElementRef<typeof RadioGroupPrimitive.Root>,
  RadioProps
>(({ items, size = "md", children, className, ui, ...props }, ref) => {
  return (
    <RadioGroup ref={ref} className={cn(className, ui?.contaier)} {...props}>
      {items
        ? items.map((item) => (
            <RadioGroupItem
              {...item}
              key={item.value}
              size={size}
              className={cn(item.className, ui?.items)}
            />
          ))
        : children}
    </RadioGroup>
  );
});
Radio.displayName = "Radio";

export { RadioGroup, RadioGroupItem, Radio };
export type { RadioGroupProps, RadioGroupItemProps, RadioProps };
