// packages/svelte/src/components/Radio/Radio.svelte
<!-- packages/svelte/src/components/Radio/Radio.svelte -->
<script lang="ts">
    import { cn } from '../../utils';
    import { 
      radioStyles, 
      radioLabelStyles, 
      type RadioCoreProps, 
      type RadioStyleProps 
    } from '@mild-ui/core';
    
    type $$Props = RadioCoreProps & RadioStyleProps & {
      value?: string;
      'on:change'?: (event: Event) => void;
    };
    
    export let checked: $$Props['checked'] = false;
    export let disabled: $$Props['disabled'] = false;
    export let required: $$Props['required'] = false;
    export let name: $$Props['name'] = undefined;
    export let value: $$Props['value'];
    export let className: $$Props['className'] = '';
    export let size: $$Props['size'] = 'md';
    
    const radioClass = cn(
      radioStyles({ size }),
      className
    );
    
    const labelClass = cn(
      radioLabelStyles({ size })
    );
  </script>
  
  <div class="flex items-center space-x-2">
    <input
      type="radio"
      class={radioClass}
      {checked}
      {disabled}
      {required}
      {name}
      {value}
      on:change
      {...$$restProps}
    />
    {#if $$slots.default}
      <slot />
    {/if}
  </div>

// packages/vue/src/components/Radio/Radio.vue
<!-- packages/vue/src/components/Radio/Radio.vue -->
<template>
    <div class="flex items-center space-x-2">
      <input
        type="radio"
        :class="radioClasses"
        :checked="checked"
        :disabled="disabled"
        :required="required"
        :name="name"
        :value="value"
        @change="onChange"
        v-bind="$attrs"
      />
      <slot v-if="$slots.default" />
      <label
        v-else-if="label"
        :for="$attrs.id as string | undefined"
        :class="labelClasses"
      >
        {{ label }}
      </label>
    </div>
  </template>
  
  <script setup lang="ts">
  import { computed } from 'vue';
  import { 
    radioStyles, 
    radioLabelStyles, 
    type RadioCoreProps, 
    type RadioStyleProps,
  } from '@mild-ui/core';
  import { cn } from '../../utils';
  
  interface Props extends RadioCoreProps, RadioStyleProps {
    label?: string;
  }
  
  const props = withDefaults(defineProps<Props>(), {
    size: 'md',
    disabled: false,
    required: false,
    checked: false,
  });
  
  const emit = defineEmits<{
    (e: 'change', value: string): void;
  }>();
  
  const radioClasses = computed(() => {
    return cn(
      radioStyles({ size: props.size }),
      props.className
    );
  });
  
  const labelClasses = computed(() => {
    return cn(
      radioLabelStyles({ size: props.size })
    );
  });
  
  const onChange = (event: Event) => {
    const target = event.target as HTMLInputElement;
    emit('change', target.value);
  };
  </script>
