// packages/react/src/components/Checkbox/Checkbox.tsx
// packages/react/src/components/Checkbox/Checkbox.tsx
import * as React from "react";
import * as CheckboxPrimitive from "@radix-ui/react-checkbox";
import { Check } from "lucide-react";
import {
  CheckboxCoreProps,
  checkboxStyles,
  CheckboxStyleProps,
  checkboxLabelStyles,
} from "@mild-ui/core";
import { cn } from "../../utils";

// Extend from core types but manually handle React-specific props
export interface CheckboxProps extends CheckboxCoreProps, CheckboxStyleProps {
  // React-specific props
  id?: string;
  onCheckedChange?: (checked: boolean | "indeterminate") => void;
  className?: string;
  label?: string;
}

// Use explicit type annotations
const Checkbox = React.forwardRef<HTMLButtonElement, CheckboxProps>(
  (props, ref) => {
    const {
      className,
      size = "md",
      label,
      checked,
      defaultChecked,
      disabled,
      required,
      name,
      value,
      indeterminate,
      id,
      onCheckedChange,
      ...restProps
    } = props;

    return (
      <div className="flex items-center space-x-2">
        <CheckboxPrimitive.Root
          ref={ref}
          id={id}
          checked={checked}
          defaultChecked={defaultChecked}
          disabled={disabled}
          required={required}
          name={name}
          value={value}
          onCheckedChange={onCheckedChange}
          className={cn(checkboxStyles({ size }), className)}
          {...restProps}
        >
          <CheckboxPrimitive.Indicator className="flex items-center justify-center">
            <Check className="h-4 w-4" />
          </CheckboxPrimitive.Indicator>
        </CheckboxPrimitive.Root>
        {label && (
          <label htmlFor={id} className={cn(checkboxLabelStyles({ size }))}>
            {label}
          </label>
        )}
      </div>
    );
  },
);

// Set a simple displayName
Checkbox.displayName = "Checkbox";

export { Checkbox };

// packages/svelte/src/components/Checkbox/Checkbox.svelte
<!-- packages/svelte/src/components/Checkbox/Checkbox.svelte -->
<script lang="ts">
    import { cn } from '../../utils';
    import { 
      checkboxStyles, 
      checkboxLabelStyles, 
      type CheckboxCoreProps, 
      type CheckboxStyleProps 
    } from '@mild-ui/core';
    
    type $$Props = CheckboxCoreProps & CheckboxStyleProps & {
      value?: string;
      'on:change'?: (event: Event) => void;
    };
    
    export let checked: $$Props['checked'] = false;
    export let disabled: $$Props['disabled'] = false;
    export let required: $$Props['required'] = false;
    export let name: $$Props['name'] = undefined;
    export let value: $$Props['value'] = undefined;
    export let indeterminate: $$Props['indeterminate'] = false;
    export let className: $$Props['className'] = '';
    export let size: $$Props['size'] = 'md';
    
    const checkboxClass = cn(
      checkboxStyles({ size }),
      className
    );
    
    const labelClass = cn(
      checkboxLabelStyles({ size })
    );
    
    $: if (indeterminate !== undefined) {
      if (typeof document !== 'undefined') {
        const element = document.getElementById($$restProps.id ?? '');
        if (element && element instanceof HTMLInputElement) {
          element.indeterminate = indeterminate;
        }
      }
    }
  </script>
  
  <div class="flex items-center space-x-2">
    <input
      type="checkbox"
      class={checkboxClass}
      {checked}
      {disabled}
      {required}
      {name}
      {value}
      on:change
      {...$$restProps}
    />
    {#if $$slots.default}
      <slot />
    {/if}
  </div>
